/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mediaplan_opus_OpusLoader */

#ifndef _Included_com_example_mediaplan_opus_OpusLoader
#define _Included_com_example_mediaplan_opus_OpusLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mediaplan_opus_OpusLoader
 * Method:    createOpusEncoder
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_example_mediaplan_opus_OpusLoader_createOpusEncoder
  (JNIEnv *, jclass, jint, jint);


JNIEXPORT void JNICALL Java_com_example_mediaplan_opus_OpusLoader_destroyOpusEncoder
        (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_example_mediaplan_opus_OpusLoader_encodeFrame
        (JNIEnv *, jclass, jlong, jshortArray, jint, jbyteArray);

JNIEXPORT jlong JNICALL Java_com_example_mediaplan_opus_OpusLoader_createOpusDecoder
        (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_com_example_mediaplan_opus_OpusLoader_destroyOpusDecoder
        (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_example_mediaplan_opus_OpusLoader_decodeFrame
        (JNIEnv *, jclass, jlong, jbyteArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
