/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mediaplan_ogg_OggLoader */

#ifndef _Included_com_example_mediaplan_ogg_OggLoader
#define _Included_com_example_mediaplan_ogg_OggLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mediaplan_ogg_OggLoader
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT jlong JNICALL Java_com_example_mediaplan_ogg_OggLoader_init
  (JNIEnv *, jclass);

JNIEXPORT jbyteArray JNICALL Java_com_example_mediaplan_ogg_OggLoader_streamPacketin
        (JNIEnv *, jclass, jlong, jbyteArray,jint,jlong);
#ifdef __cplusplus
}
#endif
#endif
